### ISSUE TITLE
ESLint: package detection strategy

### ISSUE THREAD

**Issue by wKovacs64** [epicweb-dev/config#5]
### System Info

```shell
System:
    OS: Windows 11 10.0.22621
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
    Memory: 11.37 GB / 31.92 GB
  Binaries:
    Node: 20.12.2 - ~\AppData\Local\nvs\default\node.EXE
    npm: 10.5.0 - ~\AppData\Local\nvs\default\npm.CMD
  npmPackages:
    @epic-web/config: 1.9.1 => 1.9.1 
    eslint: 8.57.0 => 8.57.0 
    vitest: 1.6.0 => 1.6.0
```

### Expected Behavior

I would expect the ESLint config to find the `vitest` package installed and conditionally apply the vitest rules.

### Actual Behavior

It does not find the `vitest` dependency and thus does not apply the vitest rules.

### Additional Context

Certain packages (e.g., `vitest`, `@playwright/test`, etc.) don't like to be imported wholesale like the [`has`](https://github.com/epicweb-dev/config/blob/87891835b2fbda65e206fdc1151feeb1c62fcfcb/eslint.js#L11) function currently does, so dynamic `import()` rejects and the config doesn't think the package is present.

I solved this in my fork using `import.meta.resolve`, which I'd be happy to PR if that's the direct you want to go, but thought I'd run it by you here first.

**Comment by kentcdodds** [comment]
Thanks for the issue! Yes, let's make sure to handle the detection better. I used to do this by looking for deps in the package.json, which I'd be ok trying as well, but I thought the current approach would be better.
